# Generated by Django 5.2.8 on 2025-12-16 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacaoEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=50)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_projetos.equipe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='membros',
            field=models.ManyToManyField(related_name='equipes', through='api_projetos.ParticipacaoEquipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=200)),
                ('status', models.CharField(default='Em andamento', max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField()),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='api_projetos.equipe')),
                ('professor_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
