# Generated by Django 5.2.8 on 2025-11-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacaoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('cliente', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('andamento', 'Em andamento'), ('concluido', 'Concluído')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField()),
            ],
        ),
    ]
