# Generated by Django 5.2.8 on 2025-11-27 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_projetos', '0001_initial'),
        ('api_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacaoprojeto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(related_name='projetos', through='api_projetos.ParticipacaoProjeto', to='api_usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='participacaoprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_projetos.projeto'),
        ),
        migrations.AlterUniqueTogether(
            name='participacaoprojeto',
            unique_together={('usuario', 'projeto')},
        ),
    ]
