# Generated by Django 5.2.8 on 2025-11-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projetos', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participacaoprojeto',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_fim_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='planejado', max_length=20),
        ),
    ]
