# Generated by Django 5.2.8 on 2025-12-02 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projetos', '0003_alter_participacaoprojeto_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='professor_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_como_professor', to=settings.AUTH_USER_MODEL),
        ),
    ]
